import streamlit as st
import requests

# 1. Page Configuration
st.set_page_config(
    page_title="Deep Research & IaC Agent",
    page_icon="🕵️‍♂️",
    layout="wide"
)

# Backend API URL
API_URL = "http://127.0.0.1:8000/research"

# 2. UI Layout
st.title("🕵️‍♂️ Local Deep Research & Terraform AI")
st.markdown("Enter a technical topic. The AI will research the web and automatically generate the corresponding Terraform infrastructure code.")

# Create a clean input box
topic = st.text_input("What do you want to build/research?", placeholder="e.g., Terraform setup for S3 Storage Lens with an Advanced Metrics dashboard in us-east-1")

# 3. Action Logic
if st.button("Run Research & Generate Terraform", type="primary"):
    if not topic:
        st.warning("Please enter a topic to research.")
    else:
        with st.spinner(f"Agents are actively researching and coding: '{topic}'... This will take a few minutes on local hardware."):
            try:
                # Send the POST request to your FastAPI backend
                response = requests.post(API_URL, json={"topic": topic})
                
                if response.status_code == 200:
                    data = response.json()
                    st.success(f"Research & Coding Complete! Status: {data['status']}")
                    st.divider()
                    
                    # 4. Create the Tabbed Interface
                    tab_report, tab_tf, tab_trail, tab_raw = st.tabs([
                        "📄 Research Report", 
                        "🛠️ Generated Terraform", 
                        "🔍 AI Search Trail",
                        "💻 Raw Scraped Data"
                    ])
                    
                    # Tab 1: Final Synthesized Report
                    with tab_report:
                        st.markdown(data['report'])
                        
                    # Tab 2: Terraform Code (The New Agent's Output)
                    with tab_tf:
                        st.subheader("Terraform Configuration (main.tf)")
                        st.code(data['terraform_code'], language="hcl")
                        
                        # Let the user download the file directly
                        st.download_button(
                            label="⬇️ Download main.tf",
                            data=data['terraform_code'],
                            file_name="main.tf",
                            mime="text/plain"
                        )
                        
                    # Tab 3: Search Trail
                    with tab_trail:
                        st.subheader("1. Sub-Queries Generated by AI")
                        for i, q in enumerate(data.get('queries', [])):
                            st.info(f"**Task {i+1}:** {q}")
                            
                        st.subheader("2. Web Sources Scraped")
                        if not data.get('sources'):
                            st.warning("No valid URLs were successfully scraped.")
                        for source in data.get('sources', []):
                            st.success(f"🔗 {source}")
                            
                    # Tab 4: Raw Markdown Data
                    with tab_raw:
                        st.markdown("This is the raw, truncated data fed into Llama 3.1 for synthesis.")
                        for i, raw_chunk in enumerate(data.get('raw_data', [])):
                            with st.expander(f"Raw Scrape Worker {i+1}"):
                                st.code(raw_chunk, language="markdown")
                        
                else:
                    st.error(f"Backend Error: {response.status_code}")
                    st.write(response.text)
                    
            except requests.exceptions.ConnectionError:
                st.error("🚨 Could not connect to the backend. Is your FastAPI server running on http://127.0.0.1:8000 ?")
            except Exception as e:
                st.error(f"An unexpected error occurred: {str(e)}")